# Generated by Django 4.2.7 on 2023-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogtable_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='imageField',
            field=models.ImageField(default='/image/abc.png', upload_to=''),
            preserve_default=False,
        ),
    ]
